
apiVersion: policy/v1

kind: PodDisruptionBudget

metadata:

  name: cartservice-pdb

  namespace: online-boutique-dev

  labels:

    app: cartservice

    component: pdb

spec:

  minAvailable: 1

  selector:

    matchLabels:

      app: cartservice

