apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-boutique
  namespace: online-boutique-dev
spec:
  schedule: "0 20 * * 1-5"   # 20h du lundi au vendredi
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-scaler
          containers:
          - name: oc
            image: quay.io/openshift/origin-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              oc scale deployment/adservice --replicas=0 -n online-boutique-dev
              oc scale deployment/cartservice --replicas=0 -n online-boutique-dev
              oc scale deployment/checkoutservice --replicas=0 -n online-boutique-dev
              oc scale deployment/currencyservice --replicas=0 -n online-boutique-dev
              oc scale deployment/emailservice --replicas=0 -n online-boutique-dev
              oc scale deployment/frontend --replicas=0 -n online-boutique-dev
              oc scale deployment/paymentservice --replicas=0 -n online-boutique-dev
              oc scale deployment/productcatalogservice --replicas=0 -n online-boutique-dev
              oc scale deployment/recommendationservice --replicas=0 -n online-boutique-dev
              oc scale deployment/redis-cart --replicas=0 -n online-boutique-dev
              oc scale deployment/shippingservice --replicas=0 -n online-boutique-dev
          restartPolicy: OnFailure
